# Generated by Django 4.2.7 on 2023-11-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_video', '0003_rename_last_login_uservideo_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='user_video.uservideo')),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user', to='user_video.uservideo')),
            ],
        ),
    ]
