# Generated by Django 4.2.7 on 2023-11-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='id',
            new_name='meeting_id',
        ),
    ]
