# Generated by Django 4.2.7 on 2023-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_video',
            new_name='UserVideo',
        ),
    ]
