# Generated by Django 4.2.7 on 2023-11-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_video', '0002_rename_user_video_uservideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservideo',
            old_name='last_login',
            new_name='date_created',
        ),
    ]
