# Generated by Django 4.2.7 on 2023-11-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_video', '0004_alter_uservideo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservideo',
            old_name='id',
            new_name='user_video_id',
        ),
    ]
